// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG0SkZTn2_1pu1abrdBGm3jxrjioJcBoo',
    appId: '1:956779848817:android:8ae66123198b6a49e427d0',
    messagingSenderId: '956779848817',
    projectId: 'cemedo-3aef4',
    storageBucket: 'cemedo-3aef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4YjsnuMQz0czvOV6S3Fm2GYvidnF-hhc',
    appId: '1:956779848817:ios:50a6daa7499a9838e427d0',
    messagingSenderId: '956779848817',
    projectId: 'cemedo-3aef4',
    storageBucket: 'cemedo-3aef4.appspot.com',
    iosClientId: '956779848817-5haj799lmqbac7nt9opih048825rg5rn.apps.googleusercontent.com',
    iosBundleId: 'com.cemedo.cemedo',
  );
}
